name: Ubuntu Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Updating package list..."
        sudo apt-get update
        echo "Installing dependencies..."
        sudo apt-get install -y build-essential

    - name: Run basic commands
      run: |
        echo "Testing environment..."
        uname -a
        gcc --version
        echo "Environment setup complete!"
